### PR TITLE
release candidate for UraLex 2.0

### PR DESCRIPTION
**Pull request by xrotwang**
The CLDF data now comes with a human readable description, see https://github.com/lexibank/uralex/blob/release-2.0/cldf/README.md

Please also check the metadata at https://github.com/lexibank/uralex/blob/release-2.0/README.md

### CODE REVIEW

**Review by kasyrj — CHANGES_REQUESTED** [review]
Mostly looks okay!

The general information of the dataset (title and author list) in README.md, .zenodo.json and the CLDF version's files should probably still be updated to reflect the information in the updated uralex_documentation.md. The new dataset has a slightly different title, and the author list is different at least in its name order.

Aside from that, the roles of the participants might also be updated slightly so that Mervi de Heer and Jyri Lehtinen are also marked as data collectors.

I also noticed that the number of cognate sets in README.md differs slightly from what they were in the previous build, which is somewhat surprising as the cognate sets (to my knowledge) should be identical with those of the previous version.

**Comment by xrotwang** [comment]
@kasyrj regarding the cognate sets: I just excluded `cogn_set` value `0` from cognate sets. That's the value in `cogn_set` when the form is `[No equivalent]`. So I'd consider this a bugfix.

**Comment by xrotwang** [comment]
@kasyrj I adapted the metadata such that it is clear(er) that the releases of this repos on Zenodo are the **primary** source of the dataset - not derived from a dataset somewhere else. With the changes in `.zenodo.json`, the correct metadata should show up as "recommended citation" on Zenodo.

**Comment by xrotwang** [comment]
@kasyrj it's also nice to see, that CI failed after changing the cognate set count: https://github.com/lexibank/uralex/actions

**Review by kasyrj — APPROVED** [review]

**Comment by kasyrj** [comment]
One additional potential issue: should Missing_UraLex2.0_refs.bib be merged with Borrowing_references.bib?

**Comment by xrotwang** [comment]
@kasyrj the bib files could be merged in `raw/` already, yes. We didn't do that right away, because I had already made local changes before Mervi added refs in her branch. OTOH, `cldf/sources.bib` is the merge of all three bib files (minus whatever entries that are not actually cited). And since only the data in `cldf/` is guaranteed to have matching references and bibkey, I wouldn't bother making the `raw/` more consistent, when the end user should go for the CLDF data anyway.

**Review by MervideHeer — CHANGES_REQUESTED** [review]
The CLDF and other materials are looking good to me. I still have two more additions I would like to make and I have made requests for them. After them, I'm happy. I have discussed with the collaborators (also involving those not using GitHub) and we think these changes benefit our future work:

We'd like to have a "clean" raw folder, therefore I propose merging the Missing_UraLex2.0_refs.bib with the Borrowing_references.bib into a single file and getting rid of the "missing" file".

For maximum visibility, I have added extra citing information into the Readme.

**Comment by MervideHeer** [comment]
> @MervideHeer I incorporated your changes into this PR - so will close the other two relating to the bib files.

Understood. Thank you!

**Comment by evoling** [comment]
@xrotwang Although I've been using git for years I haven't been part of big collaborations before: how should I go about reviewing this? Do I just go through the "files changed" tab and confirm that they look okay to me? Are all these subsequent changes showing up there, and should I wait for them to be finished, or will we keep tidying things up even after the 2.0 branch is merged?

**Comment by xrotwang** [comment]
@evoling In terms of the data, the PR should be complete. It probably doesn't make much sense to review the data files - that's partly what `cldf validate` and the tests run by github actions are for. So focusing on the human-readable stuff, READMEs, other metadata should be good enough. If anything is changed from here on, this would show up as commits under this PR and would probably be triggered by discussion here; so you would probably be aware of this.

**Review by evoling — APPROVED** [review]
There is a note-to-self in uralex_documention.md: "Also include the DOI provided for UraLex 2.0 in this release." Are we happy to leave that there? The standard citation papers are both submitted — I guess we can update this info after the papers come out, even if the data release is otherwise finalised.

**Comment by xrotwang** [comment]
@evoling I think we should encourage people to cite the dataset, too. I know I have been frustrated when following the link to a "dataset paper" and not finding the actual data there. We also should encourage people to cite exact versions of data they were using. This introduces a bit of a conundrum, though: The DOI to be assigned by Zenodo is not known when we release the repository. That's why we now have this wording: https://github.com/lexibank/uralex/blob/release-2.0/README.md#how-to-cite
Hoping people will visit https://github.com/lexibank/uralex/releases to find
- the versioned releases
- exact citation info for each version

**Comment by xrotwang** [comment]
@MervideHeer see https://github.com/lexibank/uralex/pull/9#pullrequestreview-663588823  Should the wording be changed to be less of a "note-to-self"?

**Comment by MervideHeer** [comment]
> @MervideHeer see [#9 (review)](https://github.com/lexibank/uralex/pull/9#pullrequestreview-663588823) Should the wording be changed to be less of a "note-to-self"?

@evoling 

Sorry for the style problem. I think it's good to include the "maximal" citing information. I have now modified the sentence so that it's more directed to the reader. Unfortunately, I can't compile an example full reference just yet because we don't have all pieces of information so we need to live with draft-like instructions.

**Comment by xrotwang** [comment]
So it looks like this is good to go?

**Comment by MervideHeer** [comment]
> So it looks like this is good to go?

I looked through our file changes and I see we have made all the changes we wanted. We are:

- Merging the "missing" ref entries with the Borrowing_references.bib and deleting the extra bib file.
- Adding maximum citing information in all readmes and the documentation: two papers and a mention of the soon-to-be DOI
- Using the newly updated CLDF information
- @kasyrj and @evoling have seen the changes and contributed their views.

Previously

- We added the new main Data.tsv file with loanword info and no "timing" columns. The file parses correctly. We fixed some references later. We added a reference tsv with bib-codes as well as a plain .bib file of the refs. The parts of 2.0 are symmetrical enough in relation to 1.0. We call the folder "raw".
- Python codes are updated in raw
- The Documentation markdown lives in the correct main folder
- We got rid of the ODF in raw

I cannot think of anything else to do anymore and I have crossed over all things from my checklist I summarize above. I'm finished and we are ready.

**Comment by xrotwang** [comment]
Perfect. I'll let this sit until tomorrow - off to catch a train now. Tomorrow I can make the release, and provide you with the new DOI.

**Review by MervideHeer — APPROVED** [review]
I'm making this "approved" so the flagging goes away

**Comment by MervideHeer** [comment]
> Perfect. I'll let this sit until tomorrow - off to catch a train now. Tomorrow I can make the release, and provide you with the new DOI.

Sounds good! Just on time so I can add a brand new publication with a DOI into a conference presentation. Thank you for the help and patience. Have a safe trip!

**Pull request merged**
