### PR TITLE
Added citing information in the Readme

### PR DESCRIPTION
**Pull request by MervideHeer**
I have discussed with our collaborators and we decided to add clear citing information to the readme for maximum visibility and citeability for our work.  We can update the journal information as well after the papers are being published.

### CODE REVIEW

**Comment by xrotwang** [comment]
What about adding the info to the "real" README.md, i.e. the page rendered on the landing page of the dataset on github:
https://github.com/lexibank/uralex/blob/release-2.0/README.md#how-to-cite
? I also think - for full transparency - people should cite the dataset as archived on Zenodo using the DOI and citation recommendation from Zenodo as well.

**Comment by xrotwang** [comment]
If you are happy with the [README as is in my 2.0 PR](https://github.com/lexibank/uralex/blob/release-2.0/README.md), we could close this PR and merge the 2.0 one.

**Comment by MervideHeer** [comment]
> If you are happy with the [README as is in my 2.0 PR](https://github.com/lexibank/uralex/blob/release-2.0/README.md), we could close this PR and merge the 2.0 one.

I'm happy with the information in the link! I also added a sentence to the other Documentation Readme so all Readmes have the same information. Three citing "points": the two papers and the DOI

**Comment by xrotwang** [comment]
@MervideHeer But you'd still want the citation info in two places - the README and this file?

**Comment by xrotwang** [comment]
ok

**Comment by xrotwang** [comment]
See https://github.com/lexibank/uralex/pull/9/commits/40b365886effd22ba9c13042ee3a559181c97d1b

**Pull request closed without merging**
