### PR TITLE
Branch for UraLex 2.0 update for loanword information

### PR DESCRIPTION
**Pull request by MervideHeer**
Dear UraLex editors,
I have created a new branch for the UraLex 2.0 update which concerns the loanword information. This branch should represent the information that will be a new DOI version in Zenodo.

I have included an UraLex 2.0 folder that contains the most critical files:
-The UraLex. 2.0 data files as tsv and odt files
-The Borrowing references as a simple list in a tsv as well as a BibTex file
-The UraLex 2.0 documentation as a Markdown file
-The additional information tsv-sheets for the UraLex meanings, meaning lists, meaning list descriptions, languages, language compilers, citations and citation codes. These sheets are identical to the first release because UraLex 2.0 does not make any changes to them.

As you can see, I have not changed any other UraLex files.
Should the UraLex 2.0 folder become the new "raw" of this branch?

### CODE REVIEW

**Comment by xrotwang** [comment]
Yes, I think this will go into `raw/`. I'll merge first and then move things around.

**Comment by xrotwang** [comment]
@MervideHeer It seems that two columns from `raw/Data.tsv` have been dropped in UraLex 2.0: `age_term_pq` and `age_term_aq`. Is this intentional? Or should the values of UraLex 1 be merged into the new data?

**Comment by MervideHeer** [comment]
> @MervideHeer It seems that two columns from `raw/Data.tsv` have been dropped in UraLex 2.0: `age_term_pq` and `age_term_aq`. Is this intentional? Or should the values of UraLex 1 be merged into the new data?

Hi,
I have dropped the two age-columns from the UraLex 2.0 data tsv intentionally so they shouldn't be merged. I made the same drop in the ods-file and explained it in the 2.0 documentation too. 

I also wanted to mention that UraLex 2.0 needs so checking regarding the other files before we archive  2.0 to Zenodo. We'll do this relatively soon.

**Comment by xrotwang** [comment]
Are you going to re-upload the files after checking - or is the checking going to happen in this repository?

**Comment by MervideHeer** [comment]
It is possible that something needs to be re-uploaded but I don't know more about this phase yet.

**Pull request merged**
